export * from './sr-button';
import {
  ColorFoundationUiGreenUiGreen,
  ColorFoundationNeutralPureWhite,
  ColorFoundationNeutralBlack400,
  ColorFoundationUiGreenUiGreenLightActive,
  ColorFoundationUiGreenUiGreenHover,
  ColorFoundationUiGreenUiGreenDark,
  ColorFoundationUiGreenUiGreenLightHover,
  ColorFoundationUiGreenUiGreenDarkActive,
  ColorFoundationNeutralGray400,
  ColorFoundationNeutralBlack200,
  ColorFoundationUiGreenUiGreenActive,
  ColorFoundationNeutralBlack100,
  ColorFoundationNeutralWhite300,
  ColorFoundationNeutralWhite200,
  ColorFoundationUiGreenUiGreenDarkHover,
  ColorFoundationNeutralWhite50,
  ColorFoundationNeutralGray100,
  ColorFoundationNeutralPureBlack,
} from '../../../design-tokens/js/variables.js';

export const ButtonType = {
  roundedBtn: {
    default: {
      backgroundColor: ColorFoundationUiGreenUiGreen,
      isBorder: false,
      color: ColorFoundationNeutralBlack400,
      borderRadius: 'full',
    },
    hover: {
      backgroundColor: ColorFoundationUiGreenUiGreenHover,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenHover,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationUiGreenUiGreenDark,
      isBorder: false,
      color: ColorFoundationNeutralBlack400,
      borderWidth: null,
    },
    focused: {
      backgroundColor: ColorFoundationUiGreenUiGreen,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenDarkActive,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationUiGreenUiGreenLightHover,
      isBorder: false,
      color: ColorFoundationNeutralGray400,
    },
  },
  squaredBtn: {
    default: {
      backgroundColor: ColorFoundationUiGreenUiGreen,
      isBorder: false,
      color: ColorFoundationNeutralBlack400,
      borderRadius: 'medium',
    },
    hover: {
      backgroundColor: ColorFoundationUiGreenUiGreenHover,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenHover,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationUiGreenUiGreenDark,
      isBorder: false,
      color: ColorFoundationNeutralBlack400,
      borderWidth: null,
    },
    focused: {
      backgroundColor: ColorFoundationUiGreenUiGreen,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenDarkActive,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationUiGreenUiGreenLightHover,
      isBorder: false,
      color: ColorFoundationNeutralGray400,
    },
  },
  outlinedRoundBtn: {
    default: {
      backgroundColor: ColorFoundationNeutralPureWhite,
      isBorder: true,
      color: ColorFoundationNeutralBlack400,
      borderColor: ColorFoundationUiGreenUiGreen,
      borderRadius: 'full',
      borderWidth: 'thin',
    },
    hover: {
      backgroundColor: ColorFoundationUiGreenUiGreenLightActive,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenHover,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationNeutralPureWhite,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenDarkHover,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'thin',
    },
    focused: {
      backgroundColor: ColorFoundationUiGreenUiGreen,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenDarkActive,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationUiGreenUiGreenLightHover,
      isBorder: false,
      color: ColorFoundationNeutralGray400,
    },
  },
  outlinedSquaredBtn: {
    default: {
      backgroundColor: ColorFoundationNeutralPureWhite,
      isBorder: true,
      color: ColorFoundationNeutralBlack400,
      borderColor: ColorFoundationUiGreenUiGreen,
      borderRadius: 'medium',
      borderWidth: 'thin',
    },
    hover: {
      backgroundColor: ColorFoundationUiGreenUiGreenLightActive,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenHover,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationNeutralPureWhite,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenDarkHover,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'thin',
    },
    focused: {
      backgroundColor: ColorFoundationUiGreenUiGreen,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenDarkActive,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationUiGreenUiGreenLightHover,
      isBorder: false,
      color: ColorFoundationNeutralGray400,
    },
  },
  blackRoundButton: {
    default: {
      backgroundColor: ColorFoundationNeutralBlack400,
      isBorder: false,
      color: ColorFoundationNeutralPureWhite,
      borderRadius: 'full',
    },
    hover: {
      backgroundColor: ColorFoundationNeutralBlack200,
      isBorder: true,
      borderColor: ColorFoundationNeutralBlack200,
      color: ColorFoundationNeutralPureWhite,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationNeutralGray400,
      isBorder: false,
      borderColor: ColorFoundationUiGreenUiGreenHover,
      color: ColorFoundationNeutralPureWhite,
      borderWidth: null,
    },
    focused: {
      backgroundColor: ColorFoundationNeutralBlack100,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenActive,
      color: ColorFoundationNeutralPureWhite,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationNeutralWhite300,
      isBorder: false,
      color: ColorFoundationNeutralBlack100,
    },
  },
  blackSquaredBtn: {
    default: {
      backgroundColor: ColorFoundationNeutralBlack400,
      isBorder: false,
      color: ColorFoundationNeutralPureWhite,
      borderRadius: 'medium',
    },
    hover: {
      backgroundColor: ColorFoundationNeutralBlack200,
      isBorder: true,
      borderColor: ColorFoundationNeutralBlack200,
      color: ColorFoundationNeutralPureWhite,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationNeutralGray400,
      isBorder: false,
      borderColor: ColorFoundationUiGreenUiGreenHover,
      color: ColorFoundationNeutralPureWhite,
      borderWidth: null,
    },
    focused: {
      backgroundColor: ColorFoundationNeutralBlack100,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenActive,
      color: ColorFoundationNeutralPureWhite,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationNeutralWhite300,
      isBorder: false,
      color: ColorFoundationNeutralBlack100,
    },
  },
  blackOutlinedRoundBtn: {
    default: {
      backgroundColor: ColorFoundationNeutralPureWhite,
      isBorder: true,
      color: ColorFoundationNeutralBlack400,
      borderColor: ColorFoundationNeutralBlack400,
      borderRadius: 'full',
      borderWidth: 'thin',
    },
    hover: {
      backgroundColor: ColorFoundationNeutralPureWhite,
      isBorder: true,
      color: ColorFoundationNeutralBlack400,
      borderColor: ColorFoundationNeutralBlack400,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationNeutralPureWhite,
      isBorder: true,
      color: ColorFoundationNeutralBlack400,
      borderColor: ColorFoundationNeutralBlack400,
      borderWidth: 'thin',
    },
    focused: {
      backgroundColor: ColorFoundationNeutralWhite200,
      isBorder: true,
      borderColor: ColorFoundationNeutralBlack200,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationNeutralWhite300,
      isBorder: false,
      color: ColorFoundationNeutralBlack100,
    },
  },
  blackOutlinedSquaredBtn: {
    default: {
      backgroundColor: ColorFoundationNeutralPureWhite,
      isBorder: true,
      color: ColorFoundationNeutralBlack400,
      borderColor: ColorFoundationNeutralBlack400,
      borderRadius: 'medium',
      borderWidth: 'thin',
    },
    hover: {
      backgroundColor: ColorFoundationNeutralPureWhite,
      isBorder: true,
      color: ColorFoundationNeutralBlack400,
      borderColor: ColorFoundationNeutralBlack400,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationNeutralPureWhite,
      isBorder: true,
      color: ColorFoundationNeutralBlack400,
      borderColor: ColorFoundationNeutralBlack400,
      borderWidth: 'thin',
    },
    focused: {
      backgroundColor: ColorFoundationNeutralWhite200,
      isBorder: true,
      borderColor: ColorFoundationNeutralBlack200,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationNeutralWhite300,
      isBorder: false,
      color: ColorFoundationNeutralBlack100,
    },
  },
  roundedBtnWithWhiteText: {
    default: {
      backgroundColor: ColorFoundationUiGreenUiGreen,
      isBorder: false,
      color: ColorFoundationNeutralPureWhite,
      borderRadius: 'full',
    },
    hover: {
      backgroundColor: ColorFoundationUiGreenUiGreenHover,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenHover,
      color: ColorFoundationNeutralPureWhite,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationUiGreenUiGreenDark,
      isBorder: false,
      color: ColorFoundationNeutralPureWhite,
      borderWidth: null,
    },
    focused: {
      backgroundColor: ColorFoundationUiGreenUiGreen,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenDarkActive,
      color: ColorFoundationNeutralPureWhite,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationUiGreenUiGreenLightHover,
      isBorder: false,
      color: ColorFoundationNeutralGray400,
    },
  },
  squaredBtnWithWhiteText: {
    default: {
      backgroundColor: ColorFoundationUiGreenUiGreen,
      isBorder: false,
      color: ColorFoundationNeutralPureWhite,
      borderRadius: 'medium',
    },
    hover: {
      backgroundColor: ColorFoundationUiGreenUiGreenHover,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenHover,
      color: ColorFoundationNeutralPureWhite,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationUiGreenUiGreenDark,
      isBorder: false,
      color: ColorFoundationNeutralPureWhite,
      borderWidth: null,
    },
    focused: {
      backgroundColor: ColorFoundationUiGreenUiGreen,
      isBorder: true,
      borderColor: ColorFoundationUiGreenUiGreenDarkActive,
      color: ColorFoundationNeutralPureWhite,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationUiGreenUiGreenLightHover,
      isBorder: false,
      color: ColorFoundationNeutralGray400,
    },
  },
  whiteRoundedBtn: {
    default: {
      backgroundColor: ColorFoundationNeutralWhite50,
      isBorder: false,
      color: ColorFoundationNeutralBlack400,
      borderRadius: 'full',
    },
    hover: {
      backgroundColor: ColorFoundationNeutralWhite200,
      isBorder: true,
      borderColor: ColorFoundationNeutralWhite200,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationNeutralWhite300,
      isBorder: false,
      color: ColorFoundationNeutralBlack400,
      borderWidth: null,
    },
    focused: {
      backgroundColor: ColorFoundationNeutralWhite50,
      isBorder: true,
      borderColor: ColorFoundationNeutralGray100,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationNeutralBlack400,
      isBorder: false,
      color: ColorFoundationNeutralGray100,
    },
  },
  whiteSquaredBtn: {
    default: {
      backgroundColor: ColorFoundationNeutralWhite50,
      isBorder: false,
      color: ColorFoundationNeutralBlack400,
      borderRadius: 'medium',
    },
    hover: {
      backgroundColor: ColorFoundationNeutralWhite200,
      isBorder: true,
      borderColor: ColorFoundationNeutralWhite200,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationNeutralWhite300,
      isBorder: false,
      color: ColorFoundationNeutralBlack400,
      borderWidth: null,
    },
    focused: {
      backgroundColor: ColorFoundationNeutralWhite50,
      isBorder: true,
      borderColor: ColorFoundationNeutralGray100,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationNeutralBlack400,
      isBorder: false,
      color: ColorFoundationNeutralGray100,
    },
  },
  whiteOutlineRoundedBtn: {
    default: {
      backgroundColor: ColorFoundationNeutralPureBlack,
      isBorder: true,
      color: ColorFoundationNeutralWhite50,
      borderColor: ColorFoundationNeutralWhite50,
      borderRadius: 'full',
      borderWidth: 'thin',
    },
    hover: {
      backgroundColor: ColorFoundationNeutralPureBlack,
      isBorder: true,
      borderColor: ColorFoundationNeutralWhite50,
      color: ColorFoundationNeutralWhite50,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationNeutralPureBlack,
      isBorder: true,
      borderColor: ColorFoundationNeutralWhite50,
      color: ColorFoundationNeutralWhite50,
      borderWidth: 'thin',
    },
    focused: {
      backgroundColor: ColorFoundationNeutralWhite50,
      isBorder: true,
      borderColor: ColorFoundationNeutralGray100,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationNeutralBlack400,
      isBorder: false,
      color: ColorFoundationNeutralGray100,
    },
  },
  whiteOutlineSquaredBtn: {
    default: {
      backgroundColor: ColorFoundationNeutralPureBlack,
      isBorder: true,
      color: ColorFoundationNeutralWhite50,
      borderColor: ColorFoundationNeutralWhite50,
      borderRadius: 'medium',
      borderWidth: 'thin',
    },
    hover: {
      backgroundColor: ColorFoundationNeutralPureBlack,
      isBorder: true,
      borderColor: ColorFoundationNeutralWhite50,
      color: ColorFoundationNeutralWhite50,
      borderWidth: 'thick',
    },
    pressed: {
      backgroundColor: ColorFoundationNeutralPureBlack,
      isBorder: true,
      borderColor: ColorFoundationNeutralWhite50,
      color: ColorFoundationNeutralWhite50,
      borderWidth: 'thin',
    },
    focused: {
      backgroundColor: ColorFoundationNeutralWhite50,
      isBorder: true,
      borderColor: ColorFoundationNeutralGray100,
      color: ColorFoundationNeutralBlack400,
      borderWidth: 'medium',
    },
    disabled: {
      backgroundColor: ColorFoundationNeutralBlack400,
      isBorder: false,
      color: ColorFoundationNeutralGray100,
    },
  },
};
